-- 코드를 입력하세요
# SELECT REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, REST_INFO.FAVORITES,REST_INFO.ADDRESS, ROUND(AVG(REST_REVIEW.REVIEW_SCORE),2) AS SCORE FROM REST_INFO 
# JOIN REST_REVIEW ON REST_INFO.REST_ID = REST_REVIEW.REST_ID GROUP BY REST_INFO.REST_ID HAVING REST_INFO.ADDRESS LIKE "서울%" ORDER BY SCORE DESC, REST_INFO.FAVORITES DESC;

SELECT ri.REST_ID,ri.REST_NAME,ri.FOOD_TYPE,ri.FAVORITES,ri.ADDRESS,round(avg(rr.REVIEW_SCORE),2)SCORE
from REST_INFO ri
join REST_REVIEW rr
on ri.REST_ID=rr.REST_ID
where ri.ADDRESS like "서울%"
group by ri.REST_ID
order by SCORE desc,ri.FAVORITES desc