-- 코드를 입력하세요
# SELECT YEAR(SALES_DATE) AS YEAR MONTH(SALES_DATE) AS MONTH, A.GENDER, COUNT(*) FROM USER_INFO AS A JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE),A.GENDER HAVING A.GENDER IS NOT NULL;

# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH , A.GENDER,COUNT(*) AS USERS  FROM USER_INFO AS A JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE),A.GENDER HAVING A.GENDER IS NOT NULL ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), A.GENDER;

SELECT 
    YEAR(B.SALES_DATE) AS YEAR, 
    MONTH(B.SALES_DATE) AS MONTH, 
    A.GENDER, COUNT(DISTINCT(A.USER_ID)) AS USERS 
FROM 
USER_INFO AS A JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID 
WHERE A.GENDER IS NOT NULL 
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
ORDER BY YEAR, MONTH, A.GENDER;
