-- 코드를 작성해주세요

SELECT ID, CASE WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH' WHEN SIZE_OF_COLONY > 100 THEN 'MEDIUM' WHEN SIZE_OF_COLONY >0 THEN 'LOW' END AS SIZE FROM ECOLI_DATA ORDER BY 1;

# SELECT * FROM ECOLI_DATA;