-- 코드를 작성해주세요

SELECT SUM(B.SCORE) AS SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL FROM HR_EMPLOYEES A JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO GROUP BY B.EMP_NO ORDER BY SUM(B.SCORE) DESC LIMIT 1;

# SELECT * FROM HR_EMPLOYEES WHERE EMP_NO IN (SELECT EMP_NO,SUM(SCORE) AS SCORE FROM HR_GRADE GROUP BY EMP_NO ORDER BY SUM(SCORE) DESC);